### ISSUE TITLE
comments not working as expected

### ISSUE THREAD

**Issue by panaak** [nex3/haml-mode#32]
hi there,

i wonder if i'm doing something wrong, or...

when i try to comment a line that is indented, the `comment-dwim` places the comment (`-#`) at the end of line.. it only works properly if the line is not indented..

`haml-comment-block` / `haml-uncomment-block` works right, but usually you comment / uncomment single lines.. :/

**Comment by purcell** [comment]
That's the usual behaviour of `comment-dwim` according to its documentation -- when no region is selected and the line is not empty, `comment-indent` is called. The result is the same in ruby, for example, so this isn't a `haml-mode` bug.

If you want to override it, you can probably use `whole-line-or-region` to create a version of `comment-dwim` which uses the current line as the selected region.
