### ISSUE TITLE
Indenting within attribute block throws "No catch for tag"

### ISSUE THREAD

**Issue by jletourneau** [nex3/haml-mode#33]
Version information:

* GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0, NS apple-appkit-1344.72)
* Haml mode package-version: 20141213.920

Minimal reproduction steps:

* Launch Emacs with `emacs -q` to eliminate all non-stock configs
* Load haml-mode using `M-x load-library` and path to `haml-mode.el`
* Create a new buffer `example.haml` and invoke haml-mode with `M-x haml-mode`
* Enter the following buffer contents:
```
!!! 5
%html{ lang: 'en',
class: 'foo' }
```
* With point on the last line (with the `class` attribute), invoke `indent-for-tab-command`

Result:

Error appears in mode line and `*Messages*` buffer: `No catch for tag: --cl-block-haml-indent-p--, 6` and line remains at left margin. (The same result occurs for other tags; this is just a minimal example case.)

Expected result:

Line is indented, either `haml-indent-offset` spaces beyond the indentation of the `%html` tag, or such that the "c" in `class` lines up with the "l" in `lang` on the previous line.

**Comment by purcell** [comment]
Thanks for such an excellent issue description.

I believe I've fixed this in 5e0baf7: the indent on the continuation line will be set to the column following `{`, so not quite where you might have expected it. This was the original intent, though of course this bug has masked it for a while.

**Comment by jletourneau** [comment]
Just upgraded haml-mode from Emacs' package manager, and I am no longer able to reproduce this error. Thanks for such a quick fix!

Personally, I prefer this indenting:
```
!!! 5
%html{ lang: 'en',
       class: 'foo' }
```

To the one haml-mode now produces:
```
!!! 5
%html{ lang: 'en',
      class: 'foo' }
```

But that's just because I put spaces inside my curly braces, which I realize not everyone may do. Certainly the current state is a big step up from the error that was there before. Thanks again for the fix.

**Comment by purcell** [comment]
Yeah, I agree, and it might be possible to get the former effect, but I think I want to avoid wading around deep in the code right now... :-)
