### ISSUE TITLE
Let's drop support for javascript-mode (and use js)

### ISSUE THREAD

**Issue by tarsius** [nex3/haml-mode#34]
Since `js` has been part of Emacs for a long time, most likely nobody uses it under the old name `javascript-mode` anymore. Would you accept a patch which drops the compatibility code for the latter?

**Comment by purcell** [comment]
Presumably that just means moving to a minimum of Emacs 24? Yes, that would be welcome.

**Comment by tarsius** [comment]
@purcell Do you have write permissions for this repository?

**Comment by tarsius** [comment]
> Presumably that just means moving to a minimum of Emacs 24?

A minimum of `23.2` even.

I have created a pr.

**Comment by purcell** [comment]
> Do you have write permissions for this repository?

I do, yes -- sorry for the slow reply.

**Comment by tarsius** [comment]
Slow? Some of my pull requests for issues I ran into when working on the Emacsmirror are still open years later ;-)

**Comment by purcell** [comment]
Hah, okay then!
