### ISSUE TITLE
Highlighting seems broken in Emacs 27

### ISSUE THREAD

**Issue by jdelStrother** [nex3/haml-mode#38]
Has anyone had any luck with haml-mode in Emacs 27?  For me, my haml code is almost entirely unhighlighted.  A couple of lines might gain coloring, or it might show color while I type and then lose it a moment later, but apart from that it's just lots of white text on a black background...

I can reproduce it on a fresh emacs installation from https://emacsformacosx.com/builds/all for everything from 2018-12-08 onwards.  The previous build (2018-06-13) works fine - which is somewhat unhelpful for the purposes of narrowing down the problem, because there's a massive diff between the two.

I'm currently trying it with `GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.10 Version 10.14.1 (Build 18B75)) of 2019-02-13`, and see the same problem in both GUI & terminal versions.

Anything I can do to diagnose the problem?  Has anyone had better results with recent versions?

**Comment by jdelStrother** [comment]
Quick screencast to demo the problem:

![output-2019-02-19-10 40 21](https://user-images.githubusercontent.com/2377/53009282-12820c80-3433-11e9-97b3-c89a444e29c6.gif)

Seems ok when I'm just appending to a file, goes downhill once I start editing from the top.

**Comment by purcell** [comment]
Does bf5b6c11 fix this for you?

**Comment by jdelStrother** [comment]
Yes!  Thank you 🎉

**Comment by purcell** [comment]
Great, thanks for confirming.

**Comment by angel-mora** [comment]
Hi, I am struggling with a similar issue but just confirmed my current haml-mode is within elpa folder and contains haml-mode.el file updated and containing the chunk @purcell described from issue ```bf5b6c1```. Any other info I would need to provide?

![image](https://user-images.githubusercontent.com/56136681/131387849-523dfa26-f6e9-4b84-ab16-b6626869000c.png)

**Comment by purcell** [comment]
Hi @angel-mora, do you have a working link to the example text, or a literal chunk of text you can paste here? The commit hash you referenced doesn't seem valid. I'm interested in trying to reproduce it locally without lots of typing.
