### ISSUE TITLE
Adding haml-mode to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [nex3/haml-mode#40]
Hi,

as a part of a move to add more major modes to OOTB Emacs, haml-mode was added to [NonGNU ELPA](https://elpa.nongnu.org/). I would like to ask if the maintainers of haml-mode could update the [version attribute](https://github.com/nex3/haml-mode/blob/master/haml-mode.el#L8) to a version greater than 0. The reason is that ELPA regards packages with the version `0` as [unreleased](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/README#n260). This is insofar an issue, as [sass-mode](https://elpa.nongnu.org/nongnu/sass-mode.html) depends on haml-mode, and hence cannot be installed.

**Comment by monnier** [comment]
Pi..ing?

**Comment by purcell** [comment]
Done. Having updated the `Package-Version` header and tagged a stable release, would one normally make a subsequent commit to set a `-dev` version in the header?

**Comment by monnier** [comment]
> Done. Having updated the `Package-Version` header and tagged a stable
> release, would one normally make a subsequent commit to set a `-dev` version
> in the header?

That's up to you.  (Non)GNU ELPA should handle it right either way: it
will not make a release from the commits that have "NN.MM-dev" and it
will only make a release from the commits that change the version.


        Stefan

**Comment by purcell** [comment]
Got it, thanks.
